2023-10-06 01:03:06 ERROR Traceback (most recent call last):
  File "C:\Users\notebook-heitor\anaconda3\envs\optsimflex\lib\site-packages\wandb\cli\cli.py", line 102, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\notebook-heitor\anaconda3\envs\optsimflex\lib\site-packages\wandb\cli\cli.py", line 241, in login
    wandb.setup(settings=login_settings)
  File "C:\Users\notebook-heitor\anaconda3\envs\optsimflex\lib\site-packages\wandb\sdk\wandb_setup.py", line 327, in setup
    ret = _setup(settings=settings)
  File "C:\Users\notebook-heitor\anaconda3\envs\optsimflex\lib\site-packages\wandb\sdk\wandb_setup.py", line 320, in _setup
    wl = _WandbSetup(settings=settings)
  File "C:\Users\notebook-heitor\anaconda3\envs\optsimflex\lib\site-packages\wandb\sdk\wandb_setup.py", line 303, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "C:\Users\notebook-heitor\anaconda3\envs\optsimflex\lib\site-packages\wandb\sdk\wandb_setup.py", line 114, in __init__
    self._setup()
  File "C:\Users\notebook-heitor\anaconda3\envs\optsimflex\lib\site-packages\wandb\sdk\wandb_setup.py", line 250, in _setup
    self._setup_manager()
  File "C:\Users\notebook-heitor\anaconda3\envs\optsimflex\lib\site-packages\wandb\sdk\wandb_setup.py", line 277, in _setup_manager
    self._manager = wandb_manager._Manager(settings=self._settings)
  File "C:\Users\notebook-heitor\anaconda3\envs\optsimflex\lib\site-packages\wandb\sdk\wandb_manager.py", line 138, in __init__
    self._service.start()
  File "C:\Users\notebook-heitor\anaconda3\envs\optsimflex\lib\site-packages\wandb\sdk\service\service.py", line 258, in start
    self._launch_server()
  File "C:\Users\notebook-heitor\anaconda3\envs\optsimflex\lib\site-packages\wandb\sdk\service\service.py", line 252, in _launch_server
    _sentry.reraise(e)
  File "C:\Users\notebook-heitor\anaconda3\envs\optsimflex\lib\site-packages\wandb\analytics\sentry.py", line 154, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "C:\Users\notebook-heitor\anaconda3\envs\optsimflex\lib\site-packages\wandb\sdk\service\service.py", line 250, in _launch_server
    self._wait_for_ports(fname, proc=internal_proc)
  File "C:\Users\notebook-heitor\anaconda3\envs\optsimflex\lib\site-packages\wandb\sdk\service\service.py", line 142, in _wait_for_ports
    raise ServiceStartTimeoutError(
wandb.sdk.service.service.ServiceStartTimeoutError: Timed out waiting for wandb service to start after 30.0 seconds. Try increasing the timeout with the `_service_wait` setting.

